### ISSUE TITLE
How to run tests?

### ISSUE THREAD

**Issue by adammockor** [Pompeu/dropbox-api-v2#2]
Running `node tests/index.test.js`:

```
dropbox-api-v2 git:(master) ✗ node tests/index.test.js
/Users/adam/Projekty/dropbox-api-v2/tests/index.test.js:7
describe('gel folder', function() {
^

ReferenceError: describe is not defined
    at Object.<anonymous> (/Users/adam/Projekty/dropbox-api-v2/tests/index.test.js:7:1)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:430:10)
    at startup (node.js:141:18)
    at node.js:980:3
```

**Comment by Pompeu** [comment]
Man u need install mocha for run tests,

npm install -g mocha

after, run mocha tests/index.test.js,
bacause describe is runned for mocha ok?
